name: Verify PR

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
  pull_request:
  merge_group:

jobs:
  build:
    name: 🧪 Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: 📝 Set up node
        uses: meza/action-setup-node-pnpm@main
        with:
          install: true

      - name: 🔬 Lint
        run: pnpm lint:ci

      - name: 🧪 Test
        run: pnpm test

      - name: Collect Test Reports
        uses: meza/action-collect-test-reports@main
        with:
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: 📦 Build
        run: pnpm build

      - name: Semantic Release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
