name: Verify PR

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
  pull_request:
  merge_group:

jobs:
  build:
    name: 🧪 Verify
    runs-on: meza-ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 📝 Set up node
        uses: meza/action-setup-node-pnpm@a2f4240b2835ddfaeb13b353e996e93832b5f47c # main
        with:
          install: true

      - name: 🔬 Lint
        run: pnpm lint:ci

      - name: 🧪 Test
        run: pnpm test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        with:
          files: reports/junit.xml

      - name: Code Coverage Report
        uses: davelosert/vitest-coverage-report-action@8b157684c6a6b259b97d45e72b44242865c0f6a5 # v2.12.2
        with:
          json-summary-path: reports/coverage/unit/coverage-summary.json
          json-final-path: reports/coverage/unit/coverage-final.json

      - name: 📦 Build
        run: pnpm build

      - name: Semantic Release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ github.token }}
